### ISSUE TITLE
Encode Error

### ISSUE THREAD

**Issue by cpastir** [jcarolinares/thingiverse_downloader#4]
Page: 5
https://api.thingiverse.com/search/gaslands?access_token=<REMOVED>&page=5
Traceback (most recent call last):
  File "thingiverse_downloader.py", line 319, in <module>
    search(args.keywords, args.pages)
  File "thingiverse_downloader.py", line 117, in search
    download_objects(rest_url, str(keywords+".json"), "search")
  File "thingiverse_downloader.py", line 179, in download_objects
    file.write(json.dumps(data, indent=4, sort_keys=True, ensure_ascii=False))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfd' in position 12129: ordinal not in range(128)

**Comment by cpastir** [comment]
Command
python thingiverse_downloader.py --search "gaslands" --all ALL --all-files True

**Comment by cpastir** [comment]
running the command as phython3 resolves this.
